slave:
  image: mcgizzle/stack-network
  command: bash -c "cd testbuild && sed -i -e 's|&port|6000|' network.config && stack-network join"
  tty: true
  stdin_open: true
  net: "host"
  ports: 
    - "6000:6000"
master:
  image: mcgizzle/stack-network
  command: bash -c "cd testbuild && sed -i -e 's|&port|6001|' network.config && stack-network build"
  tty: true
  stdin_open: true
  net: "host"
  ports:
    - "6001:6001"
