slave2:
  image: mcgizzle/stack-network
  command: bash -c "cd testbuild && sed -i -e 's|&port|6002|' network.config && sed -i -e 's|mwc-random|mtl|' testbuild1.cabal && stack-network join"
  tty: true
  stdin_open: true
  net: "host"
  ports: 
    - "6002:6002"
slave1:
  image: mcgizzle/stack-network
  command: bash -c "cd testbuild && sed -i -e 's|&port|6001|' network.config && stack-network join"
  tty: true
  stdin_open: true
  net: "host"
  ports: 
    - "6001:6001"
master:
  image: mcgizzle/stack-network
  command: bash -c "cd testbuild && sed -i -e 's|&port|6000|' network.config && stack-network build -n 2"
  tty: true
  stdin_open: true
  net: "host"
  ports:
    - "6000:6000"
